name: pointless

version: "0.2.0"

description: >-
  Interpreter for the Pointless programming language

homepage: https://ptls.dev

environment:
  sdk: ">=2.8.4"

dependencies:
  path: "^1.7.0"
  dartz: "^0.9.1"
  string_unescape: "^1.5.1"
